# Generated by Django 4.1.12 on 2023-10-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('href', models.URLField()),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=50)),
                ('href_full', models.URLField()),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
